version: '3.7'
services:
  app:
    image: node:latest
    container_name: nodejs
    working_dir: /usr/src/service
    volumes:
      - ./node_modules:/usr/src/service/node_modules
      - .:/usr/src/service
    environment:
      - NODE_ENV=${NODE_ENV}
    command: npm start
    ports:
      - ${NODE_PORT}:3000
